# Generated by Django 4.0.2 on 2022-02-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_topic_related_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='related_posts',
            field=models.ManyToManyField(blank=True, related_name='topics', to='posts.Post'),
        ),
    ]
