# Generated by Django 4.0.2 on 2022-02-23 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_comment_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
